# Generated by Django 5.2.4 on 2025-08-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseprogress_courses_courseprogress_user_course_unique_together'),
        ('quizzes', '0002_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='courses.lesson', verbose_name='Урок'),
        ),
    ]
