# Generated by Django 5.2.4 on 2025-08-09 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_lesson_userquizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='success_status',
            field=models.BooleanField(default=True, help_text='Укажите статус прохождения теста', verbose_name='Статус прохождения теста'),
        ),
        migrations.AddConstraint(
            model_name='userquizresult',
            constraint=models.UniqueConstraint(fields=('user', 'quiz'), name='quizzes_userquizresult_user_quiz_unique_together'),
        ),
    ]
