# Generated by Django 5.2.4 on 2025-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Введите почту', max_length=254, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус сотрудника')),
                ('vk_id', models.CharField(blank=True, max_length=63, null=True, verbose_name='Уникальный идентификатор Вконтакте')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['full_name', 'email'],
            },
        ),
    ]
