# Generated by Django 5.2.4 on 2025-08-03 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=127, verbose_name='Название курса')),
                ('description', models.TextField(help_text='Укажите описание курса', verbose_name='Описание курса')),
                ('is_published', models.BooleanField(default=False, help_text='Укажите статус курса', verbose_name='Статус курса')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title', 'description'],
                'default_related_name': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название модуля', max_length=127, verbose_name='Название модуля')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['title', 'course'],
                'default_related_name': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=127, verbose_name='Название урока')),
                ('content', models.TextField(help_text='Добавьте содержание урока', verbose_name='Содержание урока')),
                ('video_url', models.URLField(blank=True, help_text='Добавьте ссылку на занятие', null=True, verbose_name='Ссылка на занятие')),
                ('file', models.FileField(blank=True, help_text='Прикрепите файл к уроку', null=True, upload_to='lessons/', verbose_name='Файл к уроку')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['title', 'content'],
                'default_related_name': 'lessons',
            },
        ),
    ]
