# Generated by Django 5.2.4 on 2025-08-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'default_related_name': 'modules', 'ordering': ['title', 'course__title'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
    ]
