# Generated by Django 5.2.4 on 2025-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseprogress_courses_courseprogress_user_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Укажите статус курса', verbose_name='Для публикации'),
        ),
    ]
